# Generated by Django 5.2.7 on 2025-12-15 01:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(default='inverter', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_per_kwh', models.FloatField(help_text='Rate per kWh')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('time_of_day_start', models.TimeField(blank=True, null=True)),
                ('time_of_day_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(db_column='battery_device_id', default='default', max_length=50)),
                ('voltage', models.FloatField(help_text='Battery voltage in Volts')),
                ('soc', models.FloatField(help_text='State of Charge in %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_charging', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, help_text='Battery temperature in °C', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery_readings', to='power_monitor.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(db_column='alert_device_id', default='default', max_length=50)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='power_monitor.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(db_column='consumption_device_id', default='default', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('total_consumption', models.FloatField(help_text='Total consumption in kWh')),
                ('avg_power', models.FloatField(help_text='Average power in Watts')),
                ('peak_power', models.FloatField(help_text='Peak power in Watts')),
                ('min_power', models.FloatField(default=0, help_text='Minimum power in Watts')),
                ('total_cost', models.FloatField(default=0, help_text='Total cost in currency')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumption', to='power_monitor.device')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('device_identifier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(db_column='power_device_id', default='default', max_length=50)),
                ('voltage', models.FloatField(help_text='Voltage in Volts')),
                ('current', models.FloatField(help_text='Current in Amperes')),
                ('power', models.FloatField(help_text='Power in Watts')),
                ('frequency', models.FloatField(help_text='Frequency in Hz')),
                ('power_factor', models.FloatField(help_text='Power Factor (0-1)')),
                ('battery_voltage', models.FloatField(blank=True, help_text='Battery voltage', null=True)),
                ('battery_soc', models.FloatField(blank=True, help_text='Battery State of Charge %', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='power_monitor.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='power_monit_timesta_12561b_idx'), models.Index(fields=['device_identifier', '-timestamp'], name='power_monit_power_d_b54819_idx')],
            },
        ),
    ]
