# Generated by Django 5.2.7 on 2025-12-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Format: +234XXXXXXXXXX', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receive_whatsapp_alerts', models.BooleanField(default=True)),
                ('receive_email_reports', models.BooleanField(default=True)),
                ('report_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ManyToManyField(related_name='clients', to='power_monitor.device')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_consumption_kwh', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('avg_daily_consumption', models.FloatField()),
                ('peak_power', models.FloatField()),
                ('avg_power_factor', models.FloatField()),
                ('uptime_hours', models.FloatField()),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='power_monitor.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='power_monitor.device')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='alert', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='power_monitor.alert')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='power_monitor.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
